Repository frigatebird-studio/tonfura-sdk, pull requests merged in 2024-01, with the labels that each got.

#1 feat: update types
  src/constants/method.ts
  src/types/output/custom.ts
  src/types/output/ton_getAddressInformation/ReturnGetAddressInfromation.ts
  src/types/output/ton_getExtendedaddressinformation/ReturnGetExtendedaddressinformation.ts
  src/types/output/ton_getTokenData/ReturnGetTokenData.ts
  src/types/output/ton_getTransactions/ReturnGetTransactions.ts
  src/types/output/ton_getWalletinformation/ReturnGetWalletinformation.ts
  src/types/output/ton_trylocateresulttx/ReturnTrylocateresulttx.ts
  src/types/output/ton_trylocatesourcetx/ReturnTrylocatesourcetx.ts
  src/types/output/ton_trylocatetx/ReturnTrylocatetx.ts
Labels: enhancement

#3 fix: wrap response with JSONRPCResponse
  docs-md/classes/Core.md
  docs-md/classes/Tonfura.md
  docs-md/classes/TonfuraConfig.md
  docs-md/classes/TonfuraProvider.md
  docs-md/classes/Transact.md
  docs-md/enums/Network.md
  docs/assets/search.js
  docs/classes/Core.html
  docs/classes/Tonfura.html
  docs/classes/TonfuraConfig.html
  docs/classes/TonfuraProvider.html
  docs/classes/Transact.html
  docs/enums/Network.html
  docs/index.html
  docs/modules.html
  src/api/Core.ts
  src/api/Transact.ts
  src/constants/settings.ts
  src/types/JSONRPC.d.ts
  src/types/TonfuraSDK.d.ts
Labels: bug, documentation

#4 fix: correct modules naming
  src/types/json-rpc.d.ts
  src/types/tonfura-sdk.d.ts
Labels: bug
